# Generated by Django 3.2 on 2021-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0002_remove_supplier_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
