# Generated by Django 3.2 on 2021-05-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0003_auto_20210501_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_country', models.CharField(max_length=4)),
                ('continent', models.PositiveIntegerField(choices=[(5, 'Oceania'), (3, 'Africa'), (2, 'South America'), (0, 'Europe'), (1, 'North America'), (4, 'Asia'), (6, 'Antarctica'), (7, 'Unspecified')], default=7)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Monitoring.region'),
        ),
    ]
