# Generated by Django 3.2 on 2021-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0004_auto_20210501_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(1, 'North America'), (5, 'Oceania'), (2, 'South America'), (4, 'Asia'), (6, 'Antarctica'), (3, 'Africa'), (0, 'Europe'), (7, 'Unspecified')], default=7),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='region',
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.ManyToManyField(to='Monitoring.Region'),
        ),
    ]
