# Generated by Django 3.2 on 2021-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0006_auto_20210501_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='short_country',
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(3, 'Africa'), (7, 'Unspecified'), (2, 'South America'), (6, 'Antarctica'), (5, 'Oceania'), (4, 'Asia'), (0, 'Europe'), (1, 'North America')], default=7),
        ),
    ]
