# Generated by Django 3.2 on 2021-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0007_auto_20210501_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='short_name',
        ),
        migrations.AddField(
            model_name='region',
            name='short_country',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(4, 'Asia'), (0, 'Europe'), (7, 'Unspecified'), (6, 'Antarctica'), (1, 'North America'), (5, 'Oceania'), (3, 'Africa'), (2, 'South America')], default=7),
        ),
    ]
