# Generated by Django 3.2 on 2021-05-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0008_auto_20210501_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(5, 'Oceania'), (4, 'Asia'), (3, 'Africa'), (2, 'South America'), (1, 'North America'), (7, 'Unspecified'), (0, 'Europe'), (6, 'Antarctica')], default=7),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField(choices=[(28, '20:00'), (13, '12:30'), (27, '19:30'), (21, '16:30'), (11, '11:30'), (4, '8:00'), (16, '14:00'), (30, '21:00'), (17, '14:30'), (0, '6:00'), (26, '19:00'), (18, '15:00'), (19, '15:30'), (22, '17:00'), (6, '9:00'), (7, '9:30'), (29, '20:30'), (23, '17:30'), (1, '6:30'), (14, '13:00'), (24, '18:00'), (20, '16:00'), (2, '7:00'), (15, '13:30'), (8, '10:00'), (10, '11:00'), (5, '8:30'), (12, '12:00'), (25, '18:30'), (3, '7:30'), (31, '21:30'), (9, '10:30')], default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoring.supplier')),
            ],
        ),
    ]
