# Generated by Django 3.2 on 2021-05-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0009_auto_20210501_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plate',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='hour',
            field=models.PositiveIntegerField(choices=[(12, '12:00'), (2, '7:00'), (17, '14:30'), (20, '16:00'), (24, '18:00'), (26, '19:00'), (15, '13:30'), (29, '20:30'), (22, '17:00'), (8, '10:00'), (28, '20:00'), (5, '8:30'), (0, '6:00'), (3, '7:30'), (16, '14:00'), (30, '21:00'), (9, '10:30'), (13, '12:30'), (23, '17:30'), (19, '15:30'), (1, '6:30'), (21, '16:30'), (4, '8:00'), (6, '9:00'), (10, '11:00'), (31, '21:30'), (18, '15:00'), (25, '18:30'), (7, '9:30'), (11, '11:30'), (27, '19:30'), (14, '13:00')], default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(5, 'Oceania'), (4, 'Asia'), (1, 'North America'), (6, 'Antarctica'), (0, 'Europe'), (3, 'Africa'), (2, 'South America'), (7, 'Unspecified')], default=7),
        ),
    ]
