# Generated by Django 3.2 on 2021-05-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0010_auto_20210502_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hour',
            field=models.PositiveIntegerField(choices=[(14, '13:00'), (22, '17:00'), (26, '19:00'), (11, '11:30'), (8, '10:00'), (25, '18:30'), (9, '10:30'), (20, '16:00'), (13, '12:30'), (4, '8:00'), (21, '16:30'), (23, '17:30'), (27, '19:30'), (15, '13:30'), (5, '8:30'), (31, '21:30'), (7, '9:30'), (28, '20:00'), (12, '12:00'), (16, '14:00'), (30, '21:00'), (18, '15:00'), (19, '15:30'), ('6:00', '6:00'), (17, '14:30'), (6, '9:00'), (29, '20:30'), ('7:30', '7:30'), ('7:00', '7:00'), ('6:30', '6:30'), (24, '18:00'), (10, '11:00')], default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(5, 'Oceania'), (2, 'South America'), (0, 'Europe'), (7, 'Unspecified'), (6, 'Antarctica'), (1, 'North America'), (4, 'Asia'), (3, 'Africa')], default=7),
        ),
    ]
