# Generated by Django 3.2 on 2021-05-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0012_auto_20210502_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hour',
            field=models.PositiveIntegerField(choices=[('14:00', '14:00'), ('13:30', '13:30'), ('18:30', '18:30'), (0, '6:00'), ('16:30', '16:30'), ('19:30', '19:30'), ('20:30', '20:30'), ('13:00', '13:00'), ('15:30', '15:30'), ('18:00', '18:00'), ('19:00', '19:00'), ('10:30', '10:30'), ('11:30', '11:30'), ('14:30', '14:30'), ('7:00', '7:00'), ('9:00', '9:00'), ('9:30', '9:30'), ('16:00', '16:00'), ('21:00', '21:00'), ('20:00', '20:00'), ('17:30', '17:30'), ('7:30', '7:30'), ('10:00', '10:00'), ('6:30', '6:30'), ('8:00', '8:00'), ('17:00', '17:00'), ('12:00', '12:00'), ('21:30', '21:30'), ('12:30', '12:30'), ('8:30', '8:30'), ('15:00', '15:00'), ('11:00', '11:00')], default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(2, 'South America'), (7, 'Unspecified'), (5, 'Oceania'), (1, 'North America'), (4, 'Asia'), (6, 'Antarctica'), (0, 'Europe'), (3, 'Africa')], default=7),
        ),
    ]
