# Generated by Django 3.2 on 2021-05-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0018_auto_20210504_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(0, 'Europe'), (5, 'Oceania'), (6, 'Antarctica'), (1, 'North America'), (2, 'South America'), (4, 'Asia'), (3, 'Africa'), (7, 'Unspecified')], default=7),
        ),
    ]
