# Generated by Django 3.2 on 2021-05-08 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Monitoring', '0019_auto_20210508_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='continent',
            field=models.PositiveIntegerField(choices=[(1, 'North America'), (2, 'South America'), (7, 'Unspecified'), (4, 'Asia'), (6, 'Antarctica'), (5, 'Oceania'), (0, 'Europe'), (3, 'Africa')], default=7),
        ),
    ]
